# Generated by Django 5.2.7 on 2025-10-18 15:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("man_published", django.db.models.manager.Manager()),
            ],
        ),
    ]
