# Generated by Django 5.2.7 on 2025-10-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0002_alter_post_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
