# Generated by Django 5.2.7 on 2025-10-23 16:34

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0003_alter_post_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=django_jalali.db.models.jDateTimeField(
                default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DR", "draft"), ("PB", "published"), ("RJ", "rejected")],
                default="DR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
