# Generated by Django 5.2.7 on 2025-10-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0004_alter_post_created_at_alter_post_pb_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-pb_date"],
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
            },
        ),
    ]
