# Generated by Django 5.2.7 on 2025-10-23 17:27

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0005_alter_post_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="متن"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=django_jalali.db.models.jDateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="آپدیت شده"
            ),
        ),
    ]
