# Generated by Django 5.2.7 on 2025-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0006_alter_post_author_alter_post_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="اسم")),
                ("message", models.TextField(verbose_name="پیام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تماس")),
                ("subject", models.CharField(verbose_name="عنوان پیام")),
            ],
        ),
    ]
