# Generated by Django 5.2.7 on 2025-11-08 10:37

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0007_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="time",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="زمان",
            ),
            preserve_default=False,
        ),
    ]
