# Generated by Django 5.2.7 on 2025-11-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0008_ticket_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "تیکت", "verbose_name_plural": "تیکت ها"},
        ),
    ]
