# Generated by Django 5.2.7 on 2025-11-11 09:53

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0009_alter_ticket_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="نام")),
                ("cm_body", models.TextField(verbose_name="کامنت")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ آپدیت"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("active", models.BooleanField(default=False, verbose_name="تایید")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog2.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="blog2_comme_created_2de7f9_idx"
                    )
                ],
            },
        ),
    ]
