# Generated by Django 5.2.7 on 2025-11-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "blog2",
            "0011_rename_blog2_comme_created_2de7f9_idx_blog2_comment_created_at_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="blog2_comment_created_at_idx",
        ),
    ]
