# Generated by Django 5.2.7 on 2025-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0012_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="blog2_comment_created_at_idx"
            ),
        ),
    ]
