# Generated by Django 5.2.7 on 2025-11-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0013_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="blog2_comme_created_2de7f9_idx",
            old_name="blog2_comment_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog2_post_pb_date_18fc68_idx",
            old_name="blog2_post_pb_date_idx",
        ),
    ]
