# Generated by Django 5.2.7 on 2025-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blog2",
            "0014_rename_blog2_comment_created_at_idx_blog2_comme_created_2de7f9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
            },
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="blog2_comme_created_2de7f9_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["-created_at"], name="blog2_comme_created_13dfc0_idx"
            ),
        ),
    ]
