# Generated by Django 5.2.7 on 2025-11-14 07:43

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0015_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=django_jalali.db.models.jDateTimeField(
                default=jdatetime.datetime.now, verbose_name="تاریخ انتشار"
            ),
        ),
    ]
