# Generated by Django 5.2.7 on 2025-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0016_alter_post_pb_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(default=0, verbose_name="زمان مطالعه"),
        ),
    ]
