# Generated by Django 5.2.7 on 2025-11-22 09:53

import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0017_post_reading_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آپدیت"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=models.DateTimeField(
                default=jdatetime.datetime.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
        ),
    ]
