# Generated by Django 5.2.7 on 2025-11-22 10:33

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0018_alter_comment_created_at_alter_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ آپدیت"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=django_jalali.db.models.jDateTimeField(
                default=jdatetime.datetime.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="آپدیت شده"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="زمان"
            ),
        ),
    ]
