# Generated by Django 5.2.7 on 2025-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0020_postimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "عکس",
                "verbose_name_plural": "عکس ها",
            },
        ),
    ]
