# Generated by Django 5.2.7 on 2025-12-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0021_alter_postimage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تصویر",
                "verbose_name_plural": "تصاویر",
            },
        ),
    ]
