# Generated by Django 5.2.7 on 2025-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0022_alter_postimage_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postimage",
            name="blog2_posti_created_71ceb1_idx",
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["created_at"], name="blog2_posti_created_924d03_idx"
            ),
        ),
    ]
