# Generated by Django 5.2.7 on 2025-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0023_remove_postimage_blog2_posti_created_71ceb1_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "تصویر",
                "verbose_name_plural": "تصاویر",
            },
        ),
        migrations.RemoveIndex(
            model_name="postimage",
            name="blog2_posti_created_924d03_idx",
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["-created_at"], name="blog2_posti_created_71ceb1_idx"
            ),
        ),
    ]
