# Generated by Django 5.2.7 on 2025-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0024_alter_postimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="post_img/"),
        ),
    ]
