# Generated by Django 5.2.7 on 2026-01-04 11:51

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0025_alter_postimage_img"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ تولد"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=400, null=True, verbose_name="بیو"
                    ),
                ),
                (
                    "user_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_photos/",
                        verbose_name="وتصویر پروفایل",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="شغل"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editaccount",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اکانت",
                "verbose_name_plural": "اکانت ها",
            },
        ),
    ]
