# Generated by Django 5.2.7 on 2026-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0026_editaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editaccount",
            name="user_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
