# Generated by Django 5.2.7 on 2026-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0027_alter_editaccount_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("تکنولوژی", "تکنولوژی"),
                    ("هوش مصنوعی", "هوش مصنوعی"),
                    ("زبان برنامه نویسی", "زبان برنامه نویسی"),
                ],
                default="تکنولوژی",
                max_length=30,
                verbose_name="دسته بندی",
            ),
        ),
    ]
