# Generated by Django 5.2.7 on 2026-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0029_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("تکنولوژی", "تکنولوژی"),
                    ("هوش مصنوعی", "هوش مصنوعی"),
                    ("زبان برنامه نویسی", "زبان برنامه نویسی"),
                    ("سایر", "سایر"),
                ],
                default="سایر",
                max_length=30,
                verbose_name="دسته بندی",
            ),
        ),
    ]
