# Generated by Django 5.2.7 on 2026-08-28 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0030_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آپدیت"),
        ),
        migrations.AlterField(
            model_name="editaccount",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pb_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آپدیت شده"),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
        ),
    ]
